#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend Innocent.Sax
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 64820-web-01 54.173.165.199
        server 64820-web-02 54.82.120.194
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
