#!/usr/bin/env bash
# A script that loops through 1 to 10 using while

number_count=1

while [ $number_count -le 10 ]
do
    if [ $number_count -eq 4 ]
    then
        echo "bad luck"
    elif [ $number_count -eq 8 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((number_count++))
done
