#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.
#   Displays hours from 0 to 12
#   Displays minutes from 1 to 59

number_of_hour=0

while [ $number_of_hour -le 12 ]
do
  echo "Hour: $number_of_hour"
  minute=1
  while [ $minute -le 59 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( number_of_hour++ ))
done
