#!/usr/bin/env bash
# A BASH Script that runs nignx webserver as nginx and also configures nginx to
# listen to port 8080
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
